bdtln_user:
    resource: "@BdtlnUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/user
    requirements:
        _locale:    fr|en

bdtln_axe:
    resource: "@BdtlnAxeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/axe
    requirements:
        _locale:    fr|en

bdtln_project:
    resource: "@BdtlnProjectBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/project
    requirements:
        _locale:    fr|en


bdtln_administration:
    resource: "@BdtlnAdministrationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/administration
    requirements:
        _locale:    fr|en

bdtln_publication:
    resource: "@BdtlnPublicationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/publication
    requirements:
        _locale:    fr|en

bdtln_default:
    resource:   "@BdtlnDefaultBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale:    fr|en

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource:   "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register


fos_user_change_password:
    resource:   "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile