bdtln_user:
    resource: "@BdtlnUserBundle/Resources/config/routing.yml"
    prefix:   /

bdtln_default:
    resource: "@BdtlnDefaultBundle/Resources/config/routing.yml"
    prefix:   /

bdtln_axe:
    resource: "@BdtlnAxeBundle/Resources/config/routing.yml"
    prefix:   /axe

bdtln_project:
    resource: "@BdtlnProjectBundle/Resources/config/routing.yml"
    prefix:   /project

bdtln_translation:
    resource: "@BdtlnTranslationBundle/Resources/config/routing.yml"
    prefix:   /translation

bdtln_administration:
    resource: "@BdtlnAdministrationBundle/Resources/config/routing.yml"
    prefix:   /administration

bdtln_publication:
    resource: "@BdtlnPublicationBundle/Resources/config/routing.yml"
    prefix:   /publication

app:
    resource: @AppBundle/Controller/
    type:     annotation
