#The page to add a category
bdtln_user_add_category:
    path:   /add-category
    defaults:   { _controller: BdtlnUserBundle:User:add_category }
    
bdtln_user_edit_category:
    path: /edit-category/{id}
    defaults:   { _controller: BdtlnUserBundle:User:edit_category }
    
bdtln_user_display_all_categories:
    path:   /display-cagegories
    defaults:   { _controller: BdtlnUserBundle:User:display_all_categories }
    
bdtln_user_delete_category:
    path:   /delete-category/{id}
    defaults:   { _controller: BdtlnUserBundle:User:delete_category }